name: Update EDM Playlist

on:
  schedule:
    - cron: '0 0 * * *' # Draait elke dag om 00:00 UTC
  workflow_dispatch: # Hiermee kun je het script handmatig starten

jobs:
  run-script:
    runs-on: ubuntu-latest

    permissions:
      contents: write # Geeft GitHub recht om het .m3u bestand op te slaan

    steps:
    - name: Code ophalen
      uses: actions/checkout@v4

    - name: Python instellen
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Script uitvoeren
      run: python generate_m3u.py

    - name: Wijzigingen opslaan en pushen
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        git add edm_releases.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update EDM playlist" && git push)
        
